<?php
$g = include('default.php');
return array_merge($g,array(
	'Consol' => '批次',
	'Owner' => '归属',
	'Agent' => '代理',
	'Shipper' => '发件人',
	'Consignee' => '收件人',
	'Rate'=> '费率',
	'Require Pickup' => '需要取件',
	'Connote' => '运单号',
	'Ref' => '参考号',
	'Package' => '件数',
	'Items' => '商品',
	'Item Name' => '品名',
	'Value' => '价值',
	'Dec. Value' => '报关价值',
	'Currency' => '币种',
	'Weight' => '重量',
	'Tariff' => '关税',
	'Insurance' => '保险',
	'CBM' => '立方米',
	'Delay' => '延误',
	'Shipper' => '发件人',
	'Consignee' => '收件人',
	'Baby Formula' => '婴儿配方奶粉',
	'Milk Powder' => '成人奶粉',
	'Other' => '其他商品',
	'Name' => '姓名',
	'Tel' => '电话',
	'State' => '省/洲',
	'City' => '城市',
	'Postcode' => '邮编',
	'New Shipment' => '新建运单',
	'Quick Fill' => '历史记录',
));